---

- name: config > PostgreSQL configuration custom directory
  file:
    path: "{{ postgres_data_dir }}/{{ pgconf.include_dir }}"
    state: directory
    group: postgres
    owner: postgres
    mode: 0700
  with_items: "{{ postgresql_config | selectattr('include_dir', 'defined') | list }}"
  loop_control:
    loop_var: pgconf

- name: config > PostgreSQL configuration
  template:
    src: postgresql.conf.j2
    dest: "{{ postgres_data_dir }}/postgresql.conf"
    group: postgres
    owner: postgres
    mode: 0600
  register: postgresql_conf_edit

- name: config > PostgreSQL host-based authentication (hba) configuration
  template:
    src: pg_hba.conf.j2
    dest: "{{ postgres_data_dir }}/pg_hba.conf"
    group: postgres
    owner: postgres
    mode: 0600
  register: postgresql_hba_conf_edit

