---

- name: firewall > iptables in CentOS 6
  block:
    - name: iptable rules for PostgreSQL port
      iptables:
        chain: INPUT
        protocol: tcp
        destination_port: 5432
        jump: ACCEPT
        action: insert
      register: iptables_conf_edit

    - name: Save iptables rules
      command: service iptables save
      when: iptables_conf_edit is changed

  when:
    - ansible_distribution == "CentOS"
    - ansible_distribution_major_version == "6"

- name: firewall > firewalld in CentOS 7
  block:
    - name: Ensure firewalld is running
      systemd:
        name: firewalld
        state: started
        enabled: true

    - name: firewalld rule for PostgreSQL service
      firewalld:
        service: postgresql
        permanent: yes
        state: enabled
      register: firewall_conf_edit

    - name: Reload firewalld rules
      command: firewall-cmd --reload
      when: firewall_conf_edit is changed

  when:
    - ansible_distribution == "CentOS"
    - ansible_distribution_major_version == "7"

