---

- name: yum > PostgreSQL repository in CentoOS 6
  yum:
    name: https://download.postgresql.org/pub/repos/yum/reporpms/EL-6-x86_64/pgdg-redhat-repo-latest.noarch.rpm
    state: present
  when:
    - ansible_distribution == "CentOS"
    - ansible_distribution_major_version == "6"

- name: yum > PostgreSQL repository in CentoOS 7
  yum:
    name: https://download.postgresql.org/pub/repos/yum/reporpms/EL-7-x86_64/pgdg-redhat-repo-latest.noarch.rpm
    state: present
  when:
    - ansible_distribution == "CentOS"
    - ansible_distribution_major_version == "7"

