---

- src: https://github.com/xybits/ansible-role-firewall.git
  version: v0.0.1
  name: ansible-role-firewall

- src: https://github.com/xybits/ansible-role-postgresql.git
  version: v0.0.2
  name: ansible-role-postgresql

