---

# PostgreSQL Replication
postgres_password: postgres
postgres_replication_user: replicator
postgres_replication_password: replication
postgres_replication_slot: replica_stream_pg

# - PostgreSQL Configuration -
postgresql_config:
  - listen_addresses: '*'
  - max_connections: 200
  - shared_buffers: 256MB
  - wal_level: replica
  - max_wal_senders: 5
  - wal_keep_segments: 30
  - max_replication_slots: 5
  - hot_standby: on
  - hot_standby_feedback: on
  - include_dir: "conf.d"

postgresql_hba_config:
  - local   all             postgres                                         peer
  - host    all             all                      10.133.29.0/24          md5
  - host    replication     {{ postgres_replication_user }}               10.133.29.13/32         md5
  - host    replication     {{ postgres_replication_user }}               10.133.29.17/32         md5

# PostgreSQL Data
postgresql_users:
  - name: postgres
    password: "{{ postgres_password }}"
  - name: "{{ postgres_replication_user }}"
    password: "{{ postgres_replication_password }}"
    attributes: ['LOGIN', 'REPLICATION']

# Firewall config
firewalld_zone: vap

firewalld_services:
  - name: postgresql
    short: PostgreSQL Server
    description: >-
      PostgreSQL is an open source object-relational database system,
      developed as part of the POSTGRES project at the University of California at Berkeley.
    ports:
      - port: 5432

allow_services:
  - service: postgresql
    source: "10.133.29.0/24"
